import { randomUUID } from 'node:crypto';
import type { FastifyInstance, FastifyReply } from 'fastify';
import { audit, auth, batchContext, canEditBatch, canReadBatch, type AccessRequest } from './access.js';
import { getPool } from './db/client.js';

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const MONEY_RE = /^\d+(\.\d{1,2})?$/;
const cents = (value: unknown) => typeof value === 'string' && MONEY_RE.test(value) ? (() => { const [whole, fraction = ''] = value.split('.'); return Number(whole) * 100 + Number(fraction.padEnd(2, '0')); })() : null;
function message(reply: FastifyReply, code: string, text: string, status = 400) { return reply.code(status).send({ code, message: text }); }
async function batchAccess(request: AccessRequest, reply: FastifyReply, batchId: string, write = false) {
  if (!(await auth(request, reply))) return null;
  const context = await batchContext(request, batchId);
  if (!canReadBatch(context)) { await reply.code(404).send({ code: 'NOT_FOUND' }); return null; }
  if (write && !canEditBatch(context)) { await reply.code(403).send({ code: 'FORBIDDEN' }); return null; }
  if (write && (await getPool().query('SELECT status FROM collaboration_batches WHERE id=$1', [batchId])).rows[0]?.status !== 'open') { await message(reply, 'BATCH_CLOSED', '已关闭的批次不能上架商品', 409); return null; }
  return context;
}

export async function registerListingRoutes(app: FastifyInstance): Promise<void> {
  app.get<{ Params: { batchId: string } }>('/api/batches/:batchId/listings', async (request, reply) => {
    const r = request as AccessRequest; const context = await batchAccess(r, reply, request.params.batchId); if (!context) return;
    return (await getPool().query(`SELECT l.id,l.batch_id AS "batchId",l.product_id AS "productId",l.product_group_id AS "productGroupId",l.channel_id AS "channelId",l.external_url AS "externalUrl",l.display_price_cents::text AS "displayPriceCents",l.status,COALESCE(l.product_name_snapshot,p.name) AS "productName",COALESCE(l.product_group_name_snapshot,g.name) AS "productGroupName",COALESCE(json_agg(json_build_object('productId',lv.product_id,'variantName',COALESCE(lv.variant_name_snapshot,vp.variant_name),'displayPriceCents',lv.display_price_cents::text,'status',lv.status)) FILTER (WHERE lv.product_id IS NOT NULL),'[]') AS variants FROM listings l LEFT JOIN products p ON p.id=l.product_id LEFT JOIN product_groups g ON g.id=l.product_group_id LEFT JOIN listing_variants lv ON lv.listing_id=l.id LEFT JOIN products vp ON vp.id=lv.product_id WHERE l.batch_id=$1 GROUP BY l.id,p.name,g.name ORDER BY l.updated_at DESC`, [request.params.batchId])).rows;
  });
  app.post<{ Params: { batchId: string }; Body: { channelId?: unknown; productId?: unknown; productGroupId?: unknown; externalUrl?: unknown; displayPrice?: unknown; variants?: unknown } }>('/api/batches/:batchId/listings', async (request, reply) => {
    const r = request as AccessRequest; const context = await batchAccess(r, reply, request.params.batchId, true); if (!context) return;
    const body = request.body ?? {}; const productId = body.productId ? String(body.productId) : null; const groupId = body.productGroupId ? String(body.productGroupId) : null; const price = body.displayPrice === undefined || body.displayPrice === null || body.displayPrice === '' ? null : cents(body.displayPrice);
    const variants = Array.isArray(body.variants) ? body.variants as Array<{ productId?: unknown; displayPrice?: unknown; status?: unknown }> : [];
    if (!UUID_RE.test(String(body.channelId ?? '')) || (productId === null) === (groupId === null) || (productId && !UUID_RE.test(productId)) || (groupId && !UUID_RE.test(groupId)) || typeof body.externalUrl !== 'string' || !body.externalUrl.trim() || price === null || (groupId && (!variants.length || variants.some((v) => !UUID_RE.test(String(v.productId ?? '')) || cents(v.displayPrice) === null || !['listed', 'unlisted', undefined].includes(v.status as string | undefined))))) return message(reply, 'INVALID_LISTING', '请填写有效的上架商品、链接和展示价格');
    const client = await getPool().connect(); const id = randomUUID();
    try { await client.query('BEGIN'); const channel = await client.query('SELECT id FROM manual_channels WHERE id=$1 AND workspace_id=$2', [body.channelId, context.workspaceId]); if (!channel.rowCount) { await client.query('ROLLBACK'); return message(reply, 'INVALID_LISTING', '渠道不属于当前工作区'); } let productName: string | null = null; let groupName: string | null = null; const variantNames = new Map<string, string | null>(); if (productId) { const product = (await client.query('SELECT p.name,g.name AS "groupName" FROM products p LEFT JOIN product_groups g ON g.id=p.group_id WHERE p.id=$1 AND p.workspace_id=$2', [productId, context.workspaceId])).rows[0] as { name: string; groupName: string | null } | undefined; if (!product) { await client.query('ROLLBACK'); return message(reply, 'INVALID_LISTING', '商品不属于当前工作区'); } productName = product.name; groupName = product.groupName; } else { const records = await client.query('SELECT p.id,p.variant_name AS "variantName",g.name AS "groupName" FROM products p JOIN product_groups g ON g.id=p.group_id WHERE p.group_id=$1 AND p.workspace_id=$2 AND p.id=ANY($3::uuid[])', [groupId, context.workspaceId, variants.map((v) => String(v.productId))]); if (records.rowCount !== new Set(variants.map((v) => String(v.productId))).size) { await client.query('ROLLBACK'); return message(reply, 'INVALID_LISTING', '款式不属于该商品组'); } groupName = records.rows[0]?.groupName ?? null; for (const item of records.rows as Array<{ id: string; variantName: string | null }>) variantNames.set(item.id, item.variantName); } await client.query('INSERT INTO listings(id,batch_id,product_id,product_group_id,channel_id,external_url,display_price_cents,status,product_name_snapshot,product_group_name_snapshot,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,\'listed\',$8,$9,$10)', [id, request.params.batchId, productId, groupId, body.channelId, body.externalUrl.trim(), price, productName, groupName, r.access!.id]); for (const variant of variants) await client.query('INSERT INTO listing_variants(listing_id,product_id,display_price_cents,status,variant_name_snapshot) VALUES($1,$2,$3,$4,$5)', [id, variant.productId, cents(variant.displayPrice), variant.status === 'unlisted' ? 'unlisted' : 'listed', variantNames.get(String(variant.productId)) ?? null]); await client.query('INSERT INTO listing_status_events(id,listing_id,status,created_by) VALUES($1,$2,\'listed\',$3)', [randomUUID(), id, r.access!.id]); await client.query('COMMIT'); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
    await audit(context.workspaceId, r.access!.id, 'listing.create', 'listing', id, { productId, productGroupId: groupId, variantCount: variants.length }); return { id };
  });
}
