import { randomUUID } from 'node:crypto';
import type { FastifyInstance, FastifyReply } from 'fastify';
import { audit, auth, batchContext, canEditBatch, canReadBatch, type AccessRequest, type BatchContext } from './access.js';
import { getPool } from './db/client.js';

type SaleInput = { productId?: unknown; quantity?: unknown; totalPrice?: unknown; sellerUserId?: unknown; occurredAt?: unknown; note?: unknown };
type ExpenseInput = { type?: unknown; name?: unknown; amount?: unknown; payerUserId?: unknown; saleId?: unknown; occurredAt?: unknown; note?: unknown };
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i; const MONEY_RE = /^\d+(\.\d)?$/;
function asTenths(value: unknown): number | null { if (typeof value !== 'string' || !MONEY_RE.test(value)) return null; const [whole, fraction = ''] = value.split('.'); const amount = Number(whole) * 10 + Number(fraction || 0); return Number.isSafeInteger(amount) ? amount : null; }
function asMoney(value: string | number): string { const amount = Number(value); return `${Math.floor(amount / 10)}.${Math.abs(amount % 10)}`; }
function message(reply: FastifyReply, code: string, text: string, status = 400) { return reply.code(status).send({ code, message: text }); }
function optionalText(value: unknown, limit = 1000): string | null | undefined { if (value === null || value === undefined || value === '') return null; if (typeof value !== 'string' || value.trim().length > limit) return undefined; return value.trim() || null; }
function optionalUuid(value: unknown): string | null | undefined { if (value === null || value === undefined || value === '') return null; return UUID_RE.test(String(value)) ? String(value) : undefined; }
function validTime(value: unknown): string | null { if (typeof value !== 'string' || Number.isNaN(new Date(value).getTime())) return null; return new Date(value).toISOString(); }
async function requireBatch(request: AccessRequest, reply: FastifyReply, batchId: string, write = false): Promise<BatchContext | null> { if (!(await auth(request, reply))) return null; const context = await batchContext(request, batchId); if (!canReadBatch(context)) { await reply.code(404).send({ code: 'NOT_FOUND' }); return null; } if (!write) return context; if (!canEditBatch(context)) { await reply.code(403).send({ code: 'FORBIDDEN' }); return null; } const batch = (await getPool().query('SELECT status FROM collaboration_batches WHERE id=$1', [batchId])).rows[0] as { status?: string } | undefined; if (batch?.status !== 'open') { await message(reply, 'BATCH_CLOSED', '已关闭的批次不能记录交易', 409); return null; } return context; }
async function participant(client: import('pg').PoolClient, batchId: string, userId: string) { return Boolean((await client.query('SELECT 1 FROM batch_members WHERE batch_id=$1 AND user_id=$2', [batchId, userId])).rowCount); }
async function inventoryTotals(client: import('pg').PoolClient, batchId: string, productId: string) { await client.query('SELECT id FROM inventory_purchases WHERE batch_id=$1 AND product_id=$2 FOR UPDATE', [batchId, productId]); const row = (await client.query(`SELECT COALESCE((SELECT SUM(quantity) FROM inventory_purchases WHERE batch_id=$1 AND product_id=$2),0)::int AS quantity,COALESCE((SELECT SUM(total_cost_tenths) FROM inventory_purchases WHERE batch_id=$1 AND product_id=$2),0)::bigint AS cost,COALESCE((SELECT SUM(quantity) FROM inventory_adjustments WHERE batch_id=$1 AND product_id=$2),0)::int AS "adjustedQuantity",COALESCE((SELECT SUM(consumed_cost_tenths) FROM inventory_adjustments WHERE batch_id=$1 AND product_id=$2),0)::bigint AS "adjustedCost",COALESCE((SELECT SUM(s.quantity) FROM sales s LEFT JOIN sale_reversals sr ON sr.sale_id=s.id WHERE s.batch_id=$1 AND s.product_id=$2 AND sr.sale_id IS NULL),0)::int AS "soldQuantity",COALESCE((SELECT SUM(s.consumed_cost_tenths) FROM sales s LEFT JOIN sale_reversals sr ON sr.sale_id=s.id WHERE s.batch_id=$1 AND s.product_id=$2 AND sr.sale_id IS NULL),0)::bigint AS "soldCost"`, [batchId, productId])).rows[0] as { quantity: number; cost: string; adjustedQuantity: number; adjustedCost: string; soldQuantity: number; soldCost: string }; return { availableQuantity: row.quantity - row.adjustedQuantity - row.soldQuantity, remainingCost: Number(row.cost) - Number(row.adjustedCost) - Number(row.soldCost) }; }

export async function registerSalesExpenseRoutes(app: FastifyInstance): Promise<void> {
  app.get<{ Params: { batchId: string } }>('/api/batches/:batchId/sales', async (request, reply) => { const r = request as AccessRequest; const context = await requireBatch(r, reply, request.params.batchId); if (!context) return; return (await getPool().query(`SELECT s.id,s.product_id AS "productId",p.name AS "productName",s.quantity,s.total_price_tenths::text AS "totalPriceTenths",s.consumed_cost_tenths::text AS "consumedCostTenths",u.id AS "sellerUserId",u.username AS "sellerUsername",s.occurred_at AS "occurredAt",s.note,s.created_at AS "createdAt",sr.reason AS "reversalReason",sr.created_at AS "reversedAt" FROM sales s JOIN products p ON p.id=s.product_id JOIN users u ON u.id=s.seller_user_id LEFT JOIN sale_reversals sr ON sr.sale_id=s.id WHERE s.batch_id=$1 ORDER BY s.occurred_at DESC,s.created_at DESC`, [request.params.batchId])).rows.map((row: { totalPriceTenths: string; consumedCostTenths: string }) => ({ ...row, totalPrice: asMoney(row.totalPriceTenths), consumedCost: asMoney(row.consumedCostTenths) })); });
  app.post<{ Params: { batchId: string }; Body: SaleInput }>('/api/batches/:batchId/sales', async (request, reply) => { const r = request as AccessRequest; const context = await requireBatch(r, reply, request.params.batchId, true); if (!context) return; const input = request.body ?? {}; const price = asTenths(input.totalPrice); const time = validTime(input.occurredAt); const note = optionalText(input.note); if (!UUID_RE.test(String(input.productId ?? '')) || !Number.isInteger(input.quantity) || Number(input.quantity) <= 0 || price === null || !UUID_RE.test(String(input.sellerUserId ?? '')) || !time || note === undefined) return message(reply, 'INVALID_SALE', '请填写商品、数量、成交总价、卖出人和成交时间'); const client = await getPool().connect(); const id = randomUUID(); try { await client.query('BEGIN'); const product = (await client.query('SELECT 1 FROM products WHERE id=$1 AND workspace_id=$2', [input.productId, context.workspaceId])).rowCount; if (!product || !(await participant(client, request.params.batchId, String(input.sellerUserId)))) { await client.query('ROLLBACK'); return message(reply, 'INVALID_SALE', '商品或卖出人不属于当前批次'); } const totals = await inventoryTotals(client, request.params.batchId, String(input.productId)); if (Number(input.quantity) > totals.availableQuantity) { await client.query('ROLLBACK'); return message(reply, 'INSUFFICIENT_INVENTORY', '销售数量不能超过可卖数量', 409); } const consumed = Number(input.quantity) === totals.availableQuantity ? totals.remainingCost : Math.floor(totals.remainingCost * Number(input.quantity) / totals.availableQuantity); await client.query('INSERT INTO sales(id,batch_id,product_id,quantity,total_price_tenths,consumed_cost_tenths,seller_user_id,occurred_at,note,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)', [id, request.params.batchId, input.productId, input.quantity, price, consumed, input.sellerUserId, time, note, r.access!.id]); await client.query('COMMIT'); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } await audit(context.workspaceId, r.access!.id, 'sale.create', 'sale', id, { productId: input.productId, quantity: input.quantity, totalPrice: asMoney(price) }); return { id }; });
  app.post<{ Params: { batchId: string; saleId: string }; Body: { reason?: unknown } }>('/api/batches/:batchId/sales/:saleId/reversals', async (request, reply) => { const r = request as AccessRequest; const context = await requireBatch(r, reply, request.params.batchId, true); if (!context) return; const reason = optionalText(request.body?.reason, 500); if (!reason) return message(reply, 'INVALID_REVERSAL', '请填写不超过 500 个字的撤销原因'); const client = await getPool().connect(); try { await client.query('BEGIN'); const sale = (await client.query('SELECT product_id AS "productId" FROM sales WHERE id=$1 AND batch_id=$2 FOR UPDATE', [request.params.saleId, request.params.batchId])).rows[0] as { productId: string } | undefined; if (!sale) { await client.query('ROLLBACK'); return reply.code(404).send({ code: 'NOT_FOUND' }); } await inventoryTotals(client, request.params.batchId, sale.productId); if ((await client.query('SELECT 1 FROM sale_reversals WHERE sale_id=$1', [request.params.saleId])).rowCount) { await client.query('ROLLBACK'); return message(reply, 'ALREADY_REVERSED', '这笔销售已经撤销', 409); } await client.query('INSERT INTO sale_reversals(sale_id,reason,created_by) VALUES($1,$2,$3)', [request.params.saleId, reason, r.access!.id]); await client.query('COMMIT'); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } await audit(context.workspaceId, r.access!.id, 'sale.reverse', 'sale', request.params.saleId, { reason }); return { ok: true }; });
  app.get<{ Params: { batchId: string } }>('/api/batches/:batchId/expenses', async (request, reply) => { const r = request as AccessRequest; const context = await requireBatch(r, reply, request.params.batchId); if (!context) return; return (await getPool().query(`SELECT e.id,e.sale_id AS "saleId",e.type,e.name,e.amount_tenths::text AS "amountTenths",u.id AS "payerUserId",u.username AS "payerUsername",e.occurred_at AS "occurredAt",e.note,e.created_at AS "createdAt",er.reason AS "reversalReason",er.created_at AS "reversedAt" FROM expenses e JOIN users u ON u.id=e.payer_user_id LEFT JOIN expense_reversals er ON er.expense_id=e.id WHERE e.batch_id=$1 ORDER BY e.occurred_at DESC,e.created_at DESC`, [request.params.batchId])).rows.map((row: { amountTenths: string }) => ({ ...row, amount: asMoney(row.amountTenths) })); });
  app.post<{ Params: { batchId: string }; Body: ExpenseInput }>('/api/batches/:batchId/expenses', async (request, reply) => { const r = request as AccessRequest; const context = await requireBatch(r, reply, request.params.batchId, true); if (!context) return; const input = request.body ?? {}; const saleId = optionalUuid(input.saleId); const amount = asTenths(input.amount); const name = optionalText(input.name, 100); const note = optionalText(input.note); const time = validTime(input.occurredAt); const type = input.type === 'shipping' || input.type === 'custom' ? input.type : null; if (!type || !name || amount === null || !UUID_RE.test(String(input.payerUserId ?? '')) || saleId === undefined || !time || note === undefined) return message(reply, 'INVALID_EXPENSE', '请填写费用名称、金额、付款人和发生时间'); const client = await getPool().connect(); const id = randomUUID(); try { await client.query('BEGIN'); if (!(await participant(client, request.params.batchId, String(input.payerUserId)))) { await client.query('ROLLBACK'); return message(reply, 'INVALID_EXPENSE', '付款人不属于当前批次'); } if (saleId && !(await client.query('SELECT s.id FROM sales s LEFT JOIN sale_reversals sr ON sr.sale_id=s.id WHERE s.id=$1 AND s.batch_id=$2 AND sr.sale_id IS NULL', [saleId, request.params.batchId])).rowCount) { await client.query('ROLLBACK'); return message(reply, 'INVALID_EXPENSE', '关联销售无效或已撤销'); } await client.query('INSERT INTO expenses(id,batch_id,sale_id,type,name,amount_tenths,payer_user_id,occurred_at,note,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)', [id, request.params.batchId, saleId, type, name, amount, input.payerUserId, time, note, r.access!.id]); await client.query('COMMIT'); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } await audit(context.workspaceId, r.access!.id, 'expense.create', 'expense', id, { type, amount: asMoney(amount), saleId }); return { id }; });
  app.post<{ Params: { batchId: string; expenseId: string }; Body: { reason?: unknown } }>('/api/batches/:batchId/expenses/:expenseId/reversals', async (request, reply) => { const r = request as AccessRequest; const context = await requireBatch(r, reply, request.params.batchId, true); if (!context) return; const reason = optionalText(request.body?.reason, 500); if (!reason) return message(reply, 'INVALID_REVERSAL', '请填写不超过 500 个字的撤销原因'); const client = await getPool().connect(); try { await client.query('BEGIN'); if (!(await client.query('SELECT id FROM expenses WHERE id=$1 AND batch_id=$2 FOR UPDATE', [request.params.expenseId, request.params.batchId])).rowCount) { await client.query('ROLLBACK'); return reply.code(404).send({ code: 'NOT_FOUND' }); } if ((await client.query('SELECT 1 FROM expense_reversals WHERE expense_id=$1', [request.params.expenseId])).rowCount) { await client.query('ROLLBACK'); return message(reply, 'ALREADY_REVERSED', '这笔费用已经撤销', 409); } await client.query('INSERT INTO expense_reversals(expense_id,reason,created_by) VALUES($1,$2,$3)', [request.params.expenseId, reason, r.access!.id]); await client.query('COMMIT'); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } await audit(context.workspaceId, r.access!.id, 'expense.reverse', 'expense', request.params.expenseId, { reason }); return { ok: true }; });
}
