<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { showFailToast, showSuccessToast } from 'vant';
import { useRouter } from 'vue-router';
import { api } from '../api';
import { formatDateTime } from '../utils/dateTime';

type Account = { id: string; username: string; status: 'active' | 'disabled'; createdAt: string; isSystemAdmin: boolean };
const router = useRouter(); const accounts = ref<Account[]>([]); const loading = ref(true); const error = ref(''); const showCreate = ref(false); const showReset = ref(false); const showStatus = ref(false); const selected = ref<Account | null>(null); const username = ref(''); const password = ref(''); const passwordConfirm = ref(''); const saving = ref(false);
async function load() { loading.value = true; error.value = ''; try { accounts.value = (await api.get<Account[]>('/admin/accounts')).data; } catch { error.value = '账号列表加载失败'; } finally { loading.value = false; } }
function validatePassword() { if (password.value.trim().length < 8 || password.value.trim().length > 64) { showFailToast('密码需要为 8–64 位'); return false; } if (password.value !== passwordConfirm.value) { showFailToast('两次输入的密码不一致'); return false; } return true; }
function openCreate() { username.value = ''; password.value = ''; passwordConfirm.value = ''; showCreate.value = true; }
async function createAccount() { if (!username.value.trim() || !validatePassword()) return; saving.value = true; try { await api.post('/admin/accounts', { username: username.value.trim(), password: password.value }); showCreate.value = false; showSuccessToast('账号已开通'); await load(); } catch (requestError: unknown) { showFailToast((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || '账号开通失败'); } finally { saving.value = false; } }
function openReset(account: Account) { selected.value = account; password.value = ''; passwordConfirm.value = ''; showReset.value = true; }
async function resetPassword() { if (!selected.value || !validatePassword()) return; saving.value = true; try { await api.post(`/admin/accounts/${selected.value.id}/password-reset`, { password: password.value }); showReset.value = false; showSuccessToast('密码已重置，旧登录已失效'); } catch (requestError: unknown) { showFailToast((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || '密码重置失败'); } finally { saving.value = false; } }
function requestStatus(account: Account) { selected.value = account; showStatus.value = true; }
async function updateStatus() { if (!selected.value) return; saving.value = true; const status = selected.value.status === 'active' ? 'disabled' : 'active'; try { await api.patch(`/admin/accounts/${selected.value.id}/status`, { status }); showStatus.value = false; showSuccessToast(status === 'active' ? '账号已恢复' : '账号已停用'); await load(); } catch (requestError: unknown) { showFailToast((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || '账号状态更新失败'); } finally { saving.value = false; } }
onMounted(load);
</script>

<template>
  <div class="accounts-page" data-ai-id="account-management-page"><van-nav-bar title="账号管理" left-text="返回" left-arrow @click-left="router.push('/profile')" />
    <main class="content"><header><div><span>系统管理</span><h1>账号管理</h1></div><van-button type="primary" size="small" data-ai-id="account-create" @click="openCreate">开通账号</van-button></header><p class="notice">这里只显示账号和状态，不显示密码。</p>
      <div v-if="loading" class="state"><van-loading /></div><van-empty v-else-if="error" :description="error"><van-button size="small" type="primary" @click="load">重试</van-button></van-empty><van-empty v-else-if="!accounts.length" description="暂无账号" />
      <section v-else class="account-list" data-ai-id="account-list"><article v-for="account in accounts" :key="account.id" class="account-item" :data-ai-id="`account-item-${account.id}`"><div><strong>{{ account.username }}</strong><small>创建时间 {{ formatDateTime(account.createdAt) }}</small></div><div class="actions"><van-tag :type="account.status === 'active' ? 'success' : 'danger'">{{ account.status === 'active' ? '正常' : '已停用' }}</van-tag><template v-if="!account.isSystemAdmin"><van-button class="status-action" size="small" plain :type="account.status === 'active' ? 'danger' : 'primary'" :data-ai-id="`account-status-${account.id}`" @click="requestStatus(account)">{{ account.status === 'active' ? '停用' : '恢复' }}</van-button><van-popover placement="top-end" :actions="[{ text: '重置密码' }]" @select="() => openReset(account)"><van-button class="more" plain :data-ai-id="`account-actions-${account.id}`" aria-label="重置密码"><van-icon name="ellipsis" /></van-button></van-popover></template></div></article></section>
    </main>
  </div>
  <van-dialog v-model:show="showCreate" title="开通账号" show-cancel-button :confirm-button-text="saving ? '开通中' : '确认开通'" :confirm-button-disabled="saving" data-ai-id="account-create-dialog" @confirm="createAccount"><van-field v-model="username" label="用户名" placeholder="例如：benben" data-ai-id="account-create-username" /><van-field v-model="password" label="初始密码" type="password" data-ai-id="account-create-password" /><van-field v-model="passwordConfirm" label="确认密码" type="password" data-ai-id="account-create-password-confirm" /></van-dialog>
  <van-dialog v-model:show="showReset" title="重置密码" show-cancel-button :confirm-button-text="saving ? '重置中' : '确认重置'" :confirm-button-disabled="saving" data-ai-id="account-password-reset" @confirm="resetPassword"><van-field v-model="password" label="新密码" type="password" data-ai-id="account-password-reset-input" /><van-field v-model="passwordConfirm" label="确认密码" type="password" data-ai-id="account-password-reset-confirm" /></van-dialog>
  <van-dialog v-model:show="showStatus" :title="selected?.status === 'active' ? '停用账号' : '恢复账号'" show-cancel-button :confirm-button-text="selected?.status === 'active' ? '确认停用' : '确认恢复'" :confirm-button-disabled="saving" data-ai-id="account-status-confirm" @confirm="updateStatus"><p class="dialog-note">{{ selected?.status === 'active' ? `停用 ${selected?.username} 后，该账号不能继续登录。` : `恢复 ${selected?.username} 后，该账号可以重新登录。` }}</p></van-dialog>
</template>

<style scoped>
.accounts-page{min-height:100vh;background:#f5f7fb}.accounts-page :deep(.van-nav-bar){position:sticky;top:0;z-index:2}.content{padding:20px 16px 32px}.content header{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;margin-bottom:14px}.content header span,.account-item small{color:#71809a;font-size:12px}.content h1{margin:4px 0 0;font-size:24px}.content header :deep(.van-button){min-height:38px}.notice{margin:0 0 14px;padding:10px 12px;border-radius:8px;background:#edf1ff;color:#2949aa;font-size:13px}.account-list{overflow:hidden;border-radius:10px;background:#fff}.account-item{display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:68px;padding:10px 12px;border-bottom:1px solid #e4e8f0}.account-item:last-child{border:0}.account-item strong,.account-item small{display:block}.account-item strong{margin-bottom:6px;font-size:15px}.actions{display:flex;align-items:center;gap:5px}.status-action{min-width:48px;min-height:34px;padding:0 8px;font-size:12px}.more{width:36px;min-width:36px;min-height:36px;padding:0;border:0;color:#3657c8;font-size:18px}.state{display:grid;min-height:50vh;place-items:center}.dialog-note{margin:0;padding:0 16px 12px;color:#536078;font-size:13px;line-height:1.5}
</style>
