<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { showFailToast, showSuccessToast } from 'vant';
import { useRoute, useRouter } from 'vue-router';
import { api, type ManualChannel } from '../api';
import { useWorkspaceStore } from '../stores/workspace';

type ProductGroup = { id: string; name: string; variants: Array<{ id: string; name: string | null }> };
const route = useRoute(); const router = useRouter(); const store = useWorkspaceStore(); const batchId = String(route.params.id); const groupId = String(route.query.productGroupId ?? '');
const group = ref<ProductGroup | null>(null); const channels = ref<ManualChannel[]>([]); const channelId = ref(''); const externalUrl = ref(''); const price = ref(''); const variants = ref<Array<{ productId: string; name: string; displayPrice: string; listed: boolean }>>([]); const loading = ref(true); const saving = ref(false); const error = ref(''); const showChannelPicker = ref(false); const showChannelCreate = ref(false); const newChannelName = ref(''); const creatingChannel = ref(false);
const hasVariants = computed(() => variants.value.some((item) => item.name));
const listingPrice = computed(() => hasVariants.value ? variants.value.find((item) => item.listed)?.displayPrice ?? '' : price.value);
const channelName = computed(() => channels.value.find((item) => item.id === channelId.value)?.name ?? '选择渠道');
async function load() { try { if (!store.workspaces.length) await store.load(); const [groups, channel] = await Promise.all([api.get<ProductGroup[]>(`/workspaces/${store.selectedWorkspaceId}/product-groups`), api.get<ManualChannel[]>(`/batches/${batchId}/channels`)]); group.value = groups.data.find((item) => item.id === groupId) ?? null; if (!group.value) throw new Error('NOT_FOUND'); channels.value = channel.data; variants.value = group.value.variants.map((item) => ({ productId: item.id, name: item.name ?? group.value!.name, displayPrice: '', listed: true })); } catch { error.value = '上架信息加载失败，请返回后重试'; } finally { loading.value = false; } }
async function save() { if (!group.value || !channelId.value || !externalUrl.value.trim() || !/^\d+(\.\d{1,2})?$/.test(listingPrice.value) || (hasVariants.value && (!variants.value.some((item) => item.listed) || variants.value.some((item) => item.listed && !/^\d+(\.\d{1,2})?$/.test(item.displayPrice))))) return showFailToast('请填写渠道、链接和展示价格'); saving.value = true; try { const noVariant = group.value.variants.length === 1 && !group.value.variants[0].name; await api.post(`/batches/${batchId}/listings`, noVariant ? { channelId: channelId.value, productId: group.value.variants[0].id, externalUrl: externalUrl.value.trim(), displayPrice: price.value } : { channelId: channelId.value, productGroupId: group.value.id, externalUrl: externalUrl.value.trim(), displayPrice: listingPrice.value, variants: variants.value.map((item) => ({ productId: item.productId, displayPrice: item.displayPrice, status: item.listed ? 'listed' : 'unlisted' })) }); showSuccessToast('商品已上架'); await router.replace(`/batches/${batchId}/inventory`); } catch (e: unknown) { showFailToast((e as { response?: { data?: { message?: string } } }).response?.data?.message || '上架失败'); } finally { saving.value = false; } }
function chooseChannel({ selectedOptions }: { selectedOptions: Array<{ value?: string }> }) { channelId.value = selectedOptions[0]?.value ?? ''; showChannelPicker.value = false; }
async function createChannel() { const name = newChannelName.value.trim(); if (!name) return showFailToast('请填写渠道名称'); creatingChannel.value = true; try { const channel = (await api.post<ManualChannel>(`/batches/${batchId}/channels`, { name })).data; channels.value = [...channels.value, channel].sort((left, right) => left.name.localeCompare(right.name)); channelId.value = channel.id; newChannelName.value = ''; showChannelCreate.value = false; showSuccessToast('渠道已新增并选中'); } catch (requestError: unknown) { showFailToast((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || '新增渠道失败'); } finally { creatingChannel.value = false; } }
onMounted(load);
</script>
<template><div class="listing-page" data-ai-id="listing-form-page"><van-nav-bar title="上架商品" left-text="返回" left-arrow @click-left="router.push(`/batches/${batchId}/inventory`)"/><div v-if="loading" class="state"><van-loading/></div><van-empty v-else-if="error" :description="error"/><main v-else-if="group"><p class="note">上架会把当前商品关联到该批次和渠道；成交价仍以销售记录为准。</p><van-field :model-value="group.name" label="商品" readonly data-ai-id="listing-product-group"/><van-field :model-value="channelName" label="销售渠道" required readonly is-link data-ai-id="listing-channel" @click="showChannelPicker = true"><template #button><van-button size="small" plain data-ai-id="listing-channel-add" @click.stop="showChannelCreate = true">新增</van-button></template></van-field><van-field v-model="externalUrl" label="外部链接" required placeholder="https://" data-ai-id="listing-url"/><van-field v-if="!hasVariants" v-model="price" label="展示价" required inputmode="decimal" data-ai-id="listing-price"/><section v-if="hasVariants" data-ai-id="listing-variants"><h2>款式展示价</h2><div v-for="item in variants" :key="item.productId" class="variant"><van-checkbox v-model="item.listed" :data-ai-id="`listing-variant-status-${item.productId}`">{{ item.name }}</van-checkbox><van-field v-model="item.displayPrice" :disabled="!item.listed" inputmode="decimal" placeholder="展示价" :data-ai-id="`listing-variant-price-${item.productId}`"/></div></section><van-button block type="primary" :loading="saving" data-ai-id="listing-submit" @click="save">确认上架</van-button></main></div><van-popup v-model:show="showChannelPicker" position="bottom" round data-ai-id="listing-channel-picker"><van-picker title="选择销售渠道" :columns="channels.map((item) => ({ text: item.name, value: item.id }))" @confirm="chooseChannel" @cancel="showChannelPicker = false"/></van-popup><van-dialog v-model:show="showChannelCreate" title="新增销售渠道" show-cancel-button @confirm="createChannel"><van-field v-model="newChannelName" label="渠道名称" placeholder="例如：闲鱼"/></van-dialog></template>
<style scoped>.listing-page{min-height:100vh;background:#f5f7fb}.listing-page main{padding:16px}.listing-page :deep(.van-field),section{margin-bottom:12px;border-radius:10px;background:#fff}.listing-page select{width:100%;border:0;background:transparent;font:inherit}.note{margin:0 0 12px;color:#71809a;font-size:13px;line-height:1.5}section{padding:14px}h2{margin:0 0 10px;font-size:17px}.variant{display:grid;grid-template-columns:110px 1fr;gap:8px;align-items:center;min-height:56px;border-top:1px solid #e4e8f0}.variant :deep(.van-field){margin:0}.state{display:grid;min-height:60vh;place-items:center}</style>
