<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { api } from '../api';
import { useWorkspaceStore } from '../stores/workspace';

type ProductGroup = { id: string; name: string; description: string | null; images: Array<{ assetId: string; position: number; url: string | null }>; variants: Array<{ id: string; name: string | null; referencePrice: string | null }> };
const route = useRoute(); const router = useRouter(); const store = useWorkspaceStore();
const group = ref<ProductGroup | null>(null); const loading = ref(true); const error = ref(''); const showBatch = ref(false);
const openBatches = computed(() => store.batches.filter((batch) => batch.status === 'open' && ['owner', 'editor'].includes(batch.role)).map((batch) => ({ text: batch.name, value: batch.id })));
async function load() { if (!store.selectedWorkspaceId) return; loading.value = true; error.value = ''; try { group.value = (await api.get<ProductGroup[]>(`/workspaces/${store.selectedWorkspaceId}/product-groups`)).data.find((item) => item.id === route.params.id) ?? null; if (!group.value) error.value = '商品组不存在或已删除'; } catch { error.value = '商品组详情加载失败，请重试'; } finally { loading.value = false; } }
function chooseBatch({ selectedOptions }: { selectedOptions: Array<{ value?: string }> }) { const batchId = selectedOptions[0]?.value; showBatch.value = false; if (batchId && group.value) void router.push(`/batches/${batchId}/inventory/purchases/new?productGroupId=${group.value.id}`); }
onMounted(async () => { if (!store.workspaces.length) await store.load(); await load(); });
</script>
<template><div class="detail-page" data-ai-id="product-group-detail-page"><van-nav-bar title="商品组详情" left-text="返回" left-arrow data-ai-id="product-group-detail-topbar" @click-left="router.push('/products')" /><div v-if="loading" class="state"><van-loading>正在加载商品组…</van-loading></div><van-empty v-else-if="error" :description="error" data-ai-id="product-group-detail-error"><van-button type="primary" size="small" data-ai-id="product-group-detail-retry" @click="load">重试</van-button></van-empty><main v-else-if="group"><h1>{{ group.name }}</h1><p class="description">{{ group.description || '未填写描述' }}</p><section class="image-section" data-ai-id="product-group-detail-images"><h2>商品组图片</h2><div v-if="!group.images.length" class="empty-image">暂无商品组图片</div><div v-else class="image-grid"><img v-for="image in group.images" :key="image.assetId" :src="image.url || ''" alt="商品组图片" :data-ai-id="`product-group-detail-image-${image.assetId}`"></div></section><section data-ai-id="product-group-detail-variants"><h2>款式</h2><van-empty v-if="!group.variants.some((item) => item.name)" description="未添加款式" /><div v-else class="variant-list"><div v-for="item in group.variants" :key="item.id" :data-ai-id="`product-group-detail-variant-${item.id}`"><strong>{{ item.name }}</strong><span>{{ item.referencePrice === null ? '未设置参考价' : `参考价 ¥${item.referencePrice}` }}</span></div></div></section><div v-if="store.canEditProducts" class="actions"><van-button plain type="primary" data-ai-id="product-group-edit" @click="router.push(`/product-groups/${group.id}/edit`)">编辑商品组</van-button><van-button type="primary" :disabled="!openBatches.length" data-ai-id="product-group-detail-purchase" @click="showBatch = true">采购商品组</van-button></div></main></div><van-popup v-model:show="showBatch" position="bottom" round data-ai-id="product-group-detail-batch-picker"><van-picker title="选择采购批次" :columns="openBatches" @confirm="chooseBatch" @cancel="showBatch=false" /></van-popup></template>
<style scoped>.detail-page{min-height:100vh;background:#f5f7fb}.detail-page :deep(.van-nav-bar){position:sticky;top:0;z-index:2}.detail-page main{padding:20px 16px}.detail-page h1{margin:0 0 8px;font-size:25px}.description{margin:0 0 18px;color:#536078;font-size:13px;line-height:1.55}.detail-page h2{margin:0 0 9px;font-size:17px}.image-section{margin-bottom:18px}.empty-image{display:grid;height:150px;place-items:center;border:1px solid #dce2ee;border-radius:10px;background:#edf1f7;color:#7b879a;font-size:13px}.image-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.image-grid img{width:100%;height:152px;object-fit:cover;border-radius:9px;background:#edf1f7}.variant-list{overflow:hidden;margin-bottom:18px;border-radius:10px;background:#fff}.variant-list>div{display:flex;min-height:54px;align-items:center;justify-content:space-between;gap:10px;padding:0 12px;border-bottom:1px solid #e4e8f0}.variant-list>div:last-child{border-bottom:0}.variant-list strong{font-size:15px}.variant-list span{color:#536078;font-size:13px}.actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.actions :deep(.van-button){min-height:44px}.state{display:grid;min-height:60vh;place-items:center}</style>
