<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { showFailToast, showSuccessToast } from 'vant';
import { useRoute, useRouter } from 'vue-router';
import { api, type InventoryPurchase, type ManualChannel, type Product } from '../api';
import { useWorkspaceStore, type BatchMember } from '../stores/workspace';
import AppBottomNavigation from '../components/AppBottomNavigation.vue';

type Share = { userId: string; amount: string };
const route = useRoute(); const router = useRouter(); const store = useWorkspaceStore();
const batchId = String(route.params.id);
const purchaseId = route.params.purchaseId ? String(route.params.purchaseId) : '';
const isEditing = Boolean(purchaseId);
const loading = ref(true); const saving = ref(false); const error = ref(''); const dirty = ref(false);
const products = ref<Product[]>([]); const channels = ref<ManualChannel[]>([]); const participants = ref<BatchMember[]>([]);
const productId = ref(''); const channelId = ref(''); const payerUserId = ref(''); const quantity = ref('1'); const totalCost = ref(''); const purchasedOn = ref(new Date().toISOString().slice(0, 10)); const sourceUrl = ref(''); const note = ref(''); const costCorrectionReason = ref(''); const shares = ref<Share[]>([]);
const showChannelDialog = ref(false); const channelName = ref(''); const creatingChannel = ref(false);
const selectedShares = computed(() => new Set(shares.value.map((share) => share.userId)));
const shareTotal = computed(() => shares.value.reduce((sum, share) => sum + (Number(share.amount) || 0), 0));
const totalValid = computed(() => /^\d+(\.\d)?$/.test(totalCost.value) && Math.round((shareTotal.value + Number.EPSILON) * 10) === Math.round(Number(totalCost.value) * 10));
function markDirty() { dirty.value = true; }
function back() { void router.push(`/batches/${batchId}/inventory`); }
async function load() { loading.value = true; error.value = ''; try { const requests: [Promise<{ data: Product[] }>, Promise<{ data: ManualChannel[] }>, Promise<{ data: BatchMember[] }>, Promise<{ data: InventoryPurchase }> | null] = [api.get<Product[]>(`/workspaces/${store.selectedWorkspaceId}/products`), api.get<ManualChannel[]>(`/batches/${batchId}/channels`), api.get<BatchMember[]>(`/batches/${batchId}/members`), isEditing ? api.get<InventoryPurchase>(`/batches/${batchId}/purchases/${purchaseId}`) : null]; const [productResponse, channelResponse, memberResponse, purchaseResponse] = await Promise.all(requests); products.value = productResponse.data; channels.value = channelResponse.data; participants.value = memberResponse.data; if (purchaseResponse) { const purchase = purchaseResponse.data; productId.value = purchase.productId; channelId.value = purchase.channelId; payerUserId.value = purchase.payerUserId; quantity.value = String(purchase.quantity); totalCost.value = purchase.totalCost; purchasedOn.value = purchase.purchasedOn.slice(0, 10); sourceUrl.value = purchase.sourceUrl ?? ''; note.value = purchase.note ?? ''; shares.value = purchase.costShares.map((share) => ({ userId: share.userId, amount: share.amount })); } } catch { error.value = '采购表单加载失败，请返回后重试'; } finally { loading.value = false; } }
function addShare() { const participant = participants.value.find((item) => !selectedShares.value.has(item.id)); if (participant) { shares.value.push({ userId: participant.id, amount: '' }); markDirty(); } }
function removeShare(index: number) { shares.value.splice(index, 1); markDirty(); }
async function createChannel() { const name = channelName.value.trim(); if (!name) { showFailToast('请填写渠道名称'); return; } creatingChannel.value = true; try { const { data } = await api.post<ManualChannel>(`/batches/${batchId}/channels`, { name }); channels.value.push(data); channels.value.sort((a, b) => a.name.localeCompare(b.name, 'zh-CN')); channelId.value = data.id; channelName.value = ''; showChannelDialog.value = false; markDirty(); showSuccessToast('渠道已添加'); } catch (requestError: unknown) { showFailToast((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || '渠道添加失败'); } finally { creatingChannel.value = false; } }
async function save() { if (!productId.value || !channelId.value || !payerUserId.value || !/^\d+$/.test(quantity.value) || Number(quantity.value) <= 0 || !totalValid.value || !purchasedOn.value || !shares.value.length) { showFailToast('请补全采购信息，并确认成本承担合计等于总成本'); return; } saving.value = true; try { const payload = { productId: productId.value, channelId: channelId.value, payerUserId: payerUserId.value, quantity: Number(quantity.value), totalCost: totalCost.value, costShares: shares.value.map((share) => ({ userId: share.userId, amount: share.amount })), purchasedOn: purchasedOn.value, sourceUrl: sourceUrl.value.trim() || null, note: note.value.trim() || null, costCorrectionReason: costCorrectionReason.value.trim() || null }; if (isEditing) await api.patch(`/batches/${batchId}/purchases/${purchaseId}`, payload); else await api.post(`/batches/${batchId}/purchases`, payload); showSuccessToast(isEditing ? '采购已更新' : '采购已保存'); dirty.value = false; await router.replace(isEditing ? `/batches/${batchId}/inventory/${productId.value}` : `/batches/${batchId}/inventory`); } catch (requestError: unknown) { showFailToast((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || '采购保存失败'); } finally { saving.value = false; } }
onMounted(async () => { if (!store.workspaces.length) await store.load(); await load(); });
</script>

<template>
  <div class="purchase-form-page" data-ai-id="inventory-purchase-form-page"><van-nav-bar :title="isEditing ? '编辑采购' : '新增采购'" left-text="返回" left-arrow data-ai-id="inventory-purchase-form-topbar" @click-left="back" />
    <div v-if="loading" class="page-state"><van-loading>正在加载采购信息…</van-loading></div><van-empty v-else-if="error" :description="error"><van-button type="primary" size="small" @click="load">重试</van-button></van-empty>
    <main v-else class="content"><p class="form-note">付款人和成本承担人可以不同。成本承担不会自动按付款金额填写。</p><form @submit.prevent="save"><van-field v-model="productId" label="商品" required readonly :is-link="!isEditing" placeholder="选择商品" data-ai-id="inventory-product-select" @click="!isEditing && (productId = products[0]?.id || '')"><template #input><select v-model="productId" :disabled="isEditing" @change="markDirty"><option value="" disabled>选择商品</option><option v-for="product in products" :key="product.id" :value="product.id">{{ product.name }}</option></select></template></van-field><van-field v-model="channelId" class="channel-field" label="采购渠道" required readonly placeholder="选择渠道" data-ai-id="inventory-channel-select"><template #input><div class="channel-input"><select v-model="channelId" @change="markDirty"><option value="" disabled>选择渠道</option><option v-for="channel in channels" :key="channel.id" :value="channel.id">{{ channel.name }}</option></select><button type="button" class="channel-add-button" data-ai-id="inventory-channel-create" @click="showChannelDialog = true">新增</button></div></template></van-field><van-field v-model="payerUserId" label="付款人" required readonly is-link placeholder="选择付款人" data-ai-id="inventory-payer-select"><template #input><select v-model="payerUserId" @change="markDirty"><option value="" disabled>选择付款人</option><option v-for="participant in participants" :key="participant.id" :value="participant.id">{{ participant.username }}</option></select></template></van-field><van-field v-model="quantity" label="数量" required type="digit" placeholder="例如：1" data-ai-id="inventory-quantity" @update:model-value="markDirty" /><van-field v-model="totalCost" label="总成本" required inputmode="decimal" placeholder="例如：60.0" data-ai-id="inventory-total-cost" @update:model-value="markDirty"><template #button><span class="cost-unit">元</span></template></van-field>
      <section class="share-section" data-ai-id="inventory-cost-share-list"><div class="section-head"><div><strong>成本由谁承担</strong><small>必填，合计必须等于总成本</small></div><van-button plain size="small" :disabled="shares.length >= participants.length" data-ai-id="inventory-cost-share-add" @click="addShare">添加成员</van-button></div><p v-if="!shares.length" class="share-empty">请添加至少一位承担成本的成员。</p><div v-for="(share, index) in shares" :key="share.userId" class="share-row"><select v-model="share.userId" :data-ai-id="`inventory-cost-share-member-${share.userId}`" @change="markDirty"><option v-for="participant in participants" :key="participant.id" :value="participant.id" :disabled="selectedShares.has(participant.id) && participant.id !== share.userId">{{ participant.username }}</option></select><input v-model="share.amount" inputmode="decimal" placeholder="承担金额" :data-ai-id="`inventory-cost-share-amount-${share.userId}`" @input="markDirty"><button type="button" class="remove-share" :data-ai-id="`inventory-cost-share-remove-${share.userId}`" aria-label="删除成本承担人" @click="removeShare(index)"><van-icon name="delete-o" /></button></div><p class="share-total" data-ai-id="inventory-cost-share-total">已承担 ¥{{ shareTotal.toFixed(1) }} / 总成本 ¥{{ totalCost || '0.0' }} <span :class="{ valid: totalValid }">{{ totalValid ? '已一致' : '待核对' }}</span></p></section>
      <van-field v-model="purchasedOn" label="采购日期" required type="date" data-ai-id="inventory-purchased-at" @update:model-value="markDirty" /><van-field v-if="isEditing" v-model="costCorrectionReason" label="修改成本原因" type="textarea" rows="2" placeholder="仅修改总成本时必填" data-ai-id="inventory-cost-correction-reason" @update:model-value="markDirty" /><van-field v-model="sourceUrl" label="来源链接" placeholder="可选" data-ai-id="inventory-source-url" @update:model-value="markDirty" /><van-field v-model="note" label="备注" type="textarea" rows="2" placeholder="可选" data-ai-id="inventory-note" @update:model-value="markDirty" /><div class="form-footer"><van-button block type="primary" native-type="submit" :loading="saving" data-ai-id="inventory-purchase-submit">{{ isEditing ? '保存修改' : '保存采购' }}</van-button><van-button block plain data-ai-id="inventory-purchase-cancel" @click="back">取消</van-button></div></form></main>
  </div>
  <van-dialog v-model:show="showChannelDialog" title="新增渠道" show-cancel-button :confirm-button-loading="creatingChannel" data-ai-id="inventory-channel-create-dialog" @confirm="createChannel"><van-field v-model="channelName" label="渠道名称" placeholder="例如：闲鱼" /></van-dialog>
  <AppBottomNavigation />
</template>

<style scoped>
.purchase-form-page { min-height:100vh; padding-bottom:66px; background:#f5f7fb; }.purchase-form-page :deep(.van-nav-bar) { position:sticky; top:0; z-index:2; }.content { padding:20px 16px 32px; }.form-note { margin:0 0 16px; padding:10px 12px; border-radius:8px; background:#edf1ff; color:#2949aa; font-size:13px; }.content :deep(.van-field) { margin-bottom:10px; border:1px solid #cfd6e2; border-radius:9px; background:#fff; }.content select,.share-row select,.share-row input { width:100%; min-height:38px; border:0; background:transparent; color:#172033; font:inherit; }.channel-input { display:flex; align-items:center; gap:8px; width:100%; }.channel-input select { min-width:0; flex:1; }.channel-add-button { flex:0 0 auto; min-width:44px; min-height:44px; padding:0 4px; border:0; background:transparent; color:#3657c8; font:inherit; font-size:14px; }.channel-add-button:focus-visible { outline:2px solid #3657c8; outline-offset:-2px; }.cost-unit { padding-left:8px; color:#536078; }.share-section { margin:18px 0; padding:14px 12px; border-radius:10px; background:#fff; }.section-head { display:flex; align-items:flex-start; justify-content:space-between; gap:10px; }.section-head strong,.section-head small { display:block; }.section-head small { margin-top:3px; color:#71809a; font-size:12px; }.share-empty { color:#71809a; font-size:13px; }.share-row { display:grid; grid-template-columns:minmax(0,1fr) minmax(0,1fr) 44px; gap:7px; align-items:center; margin-top:10px; padding:0 0 8px; border-bottom:1px solid #e4e8f0; }.share-row input,.share-row select { min-width:0; min-height:44px; padding:0 7px; border:1px solid #cfd6e2; border-radius:7px; }.remove-share { display:grid; width:44px; height:44px; place-items:center; padding:0; border:0; border-radius:7px; background:transparent; color:#b42318; font-size:20px; }.remove-share:focus-visible { outline:2px solid #b42318; outline-offset:1px; }.share-total { margin:12px 0 0; color:#536078; font-size:12px; }.share-total span { margin-left:5px; color:#b42318; }.share-total .valid { color:#16803c; }.form-footer { display:grid; gap:10px; margin-top:22px; }.form-footer :deep(.van-button) { min-height:44px; }.page-state { display:grid; min-height:60vh; place-items:center; }
</style>
