<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { showFailToast, showSuccessToast } from 'vant';
import { useRoute, useRouter } from 'vue-router';
import { api, type InventoryItem } from '../api';
import type { BatchMember } from '../stores/workspace';
import DangerConfirmDialog from '../components/DangerConfirmDialog.vue';
import { localDateTime } from '../utils/dateTime';

type Consumption = { productId: string; quantity: number };
type Item = { id: string; name: string; quantity: number; cost: string; linkEnabled: boolean; consumptions: Consumption[] };
const route = useRoute(); const router = useRouter(); const batchId = computed(() => String(route.params.id));
const loading = ref(true); const saving = ref(false); const error = ref(''); const inventory = ref<InventoryItem[]>([]); const members = ref<BatchMember[]>([]);
const totalPrice = ref(''); const sellerUserId = ref(''); const occurredAt = ref(localDateTime()); const salesChannel = ref(''); const feeMode = ref<'none' | 'percentage' | 'amount'>('none'); const feeValue = ref(''); const note = ref('');
const items = ref<Item[]>([]); const showPicker = ref(false); const pickerItemId = ref(''); const pickedIds = ref<string[]>([]); const removeTarget = ref<{ type: 'item' | 'consumption'; itemId: string; productId?: string } | null>(null);
const showMismatch = ref(false); let forceSave = false;
let sequence = 0;
const moneyPattern = /^\d+(\.\d{1,2})?$/;
const selectedItem = computed(() => items.value.find((item) => item.id === pickerItemId.value) ?? null);
function itemInventory(item: Item) { return item.consumptions.map((consumption) => ({ ...consumption, product: inventory.value.find((product) => product.productId === consumption.productId) })).filter((entry) => entry.product); }
function addItem() { items.value.push({ id: `item-${sequence++}`, name: '', quantity: 1, cost: '', linkEnabled: false, consumptions: [] }); }
function askRemoveItem(itemId: string) { removeTarget.value = { type: 'item', itemId }; }
function askRemoveConsumption(itemId: string, productId: string) { removeTarget.value = { type: 'consumption', itemId, productId }; }
function confirmRemove() { const target = removeTarget.value; if (!target) return; const item = items.value.find((value) => value.id === target.itemId); if (target.type === 'item') items.value = items.value.filter((value) => value.id !== target.itemId); else if (item) item.consumptions = item.consumptions.filter((value) => value.productId !== target.productId); removeTarget.value = null; }
function setQuantity(item: Item, value: number) { item.quantity = Math.max(1, value); }
function availableFor(item: Item, productId: string) { const product = inventory.value.find((value) => value.productId === productId); const usedElsewhere = items.value.filter((value) => value.id !== item.id).flatMap((value) => value.consumptions).filter((value) => value.productId === productId).reduce((sum, value) => sum + value.quantity, 0); return Math.max(0, (product?.availableQuantity ?? 0) - usedElsewhere); }
function enableLink(item: Item) { item.linkEnabled = !item.linkEnabled; if (!item.linkEnabled) item.consumptions = []; }
function openPicker(item: Item) { pickerItemId.value = item.id; pickedIds.value = item.consumptions.map((value) => value.productId); showPicker.value = true; }
function confirmPicker() { const item = selectedItem.value; if (!item) return; item.consumptions = pickedIds.value.map((productId) => ({ productId, quantity: item.consumptions.find((value) => value.productId === productId)?.quantity ?? 1 })); showPicker.value = false; }
function updateConsumption(item: Item, productId: string, value: number) { const consumption = item.consumptions.find((entry) => entry.productId === productId); if (consumption) consumption.quantity = Math.max(1, Math.min(availableFor(item, productId), value)); }
function canFillCost(item: Item) { return item.linkEnabled && item.consumptions.some((value) => value.quantity >= 1); }
function fillCost(item: Item) { if (!canFillCost(item)) return; const amount = itemInventory(item).reduce((sum, entry) => sum + Number(entry.product?.totalCost ?? 0) * entry.quantity / Math.max(1, entry.product?.availableQuantity ?? 1), 0) * item.quantity; item.cost = amount.toFixed(2); }
function calculatedFee() { const price = Number(totalPrice.value); const value = Number(feeValue.value); if (!price || !value) return 0; return feeMode.value === 'percentage' ? Math.round(price * value) / 100 : value; }
const feePreview = computed(() => { if (feeMode.value === 'none' || !feeValue.value.trim() || !moneyPattern.test(feeValue.value)) return null; const price = Number(totalPrice.value); if (!price) return null; return calculatedFee(); });
const receivedPreview = computed(() => { const fee = feePreview.value; return fee === null ? null : Number(totalPrice.value) - fee; });
function quantityMismatch(item: Item) { return item.consumptions.some((value) => value.quantity !== item.quantity); }
async function load() { loading.value = true; error.value = ''; try { const [inventoryResult, membersResult] = await Promise.all([api.get<InventoryItem[]>(`/batches/${batchId.value}/inventory`), api.get<BatchMember[]>(`/batches/${batchId.value}/members`)]); inventory.value = inventoryResult.data.filter((item) => item.availableQuantity > 0); members.value = membersResult.data; sellerUserId.value = members.value[0]?.id ?? ''; if (!items.value.length) addItem(); } catch { error.value = '快速售出表单加载失败，请重试'; } finally { loading.value = false; } }
async function save() { if (!items.value.length || !moneyPattern.test(totalPrice.value) || !sellerUserId.value || items.value.some((item) => !item.name.trim() || !moneyPattern.test(item.cost.trim()))) { showFailToast('请填写商品、本单成本、成交总价和卖出人'); return; } if (feeMode.value !== 'none' && (!moneyPattern.test(feeValue.value) || calculatedFee() > Number(totalPrice.value))) { showFailToast('手续费无效'); return; } if (!forceSave && items.value.some(quantityMismatch)) { showMismatch.value = true; return; } forceSave = false; saving.value = true; try { const { data } = await api.post<{ id: string }>(`/batches/${batchId.value}/quick-sales`, { totalPrice: totalPrice.value, sellerUserId: sellerUserId.value, occurredAt: new Date(occurredAt.value).toISOString(), salesChannel: salesChannel.value.trim() || null, feeMode: feeMode.value === 'none' ? null : feeMode.value, feeRate: feeMode.value === 'percentage' ? feeValue.value : null, feeAmount: feeMode.value === 'amount' ? feeValue.value : null, note: note.value.trim() || null, items: items.value.map((item) => ({ name: item.name.trim(), quantity: item.quantity, cost: item.cost.trim(), inventoryConsumptions: item.consumptions })) }); showSuccessToast('快速售出已保存'); await router.replace(`/batches/${batchId.value}/quick-sales/${data.id}`); } catch (requestError: unknown) { showFailToast((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || '快速售出保存失败'); } finally { saving.value = false; } }
function confirmMismatch() { showMismatch.value = false; forceSave = true; void save(); }
onMounted(load);
</script>

<template>
  <div class="quick-sale-form-page" data-ai-id="quick-sale-form-page">
    <van-nav-bar title="快速售出" left-text="返回" left-arrow data-ai-id="quick-sale-form-topbar" @click-left="router.push(`/batches/${batchId}/transactions`)" />
    <div v-if="loading" class="state"><van-loading /></div><van-empty v-else-if="error" :description="error"><van-button size="small" type="primary" @click="load">重试</van-button></van-empty>
    <main v-else class="content"><p class="notice" data-ai-id="quick-sale-form-notice">可直接登记组合售出；只有关联库存的数量会扣减库存。</p>
      <section class="card" data-ai-id="quick-sale-form-order"><van-field v-model="totalPrice" label="成交总价" required inputmode="decimal" placeholder="例如：399.00" data-ai-id="quick-sale-total-price"><template #button>元</template></van-field><van-field :model-value="members.find((member) => member.id === sellerUserId)?.username || ''" label="卖出人" required readonly is-link data-ai-id="quick-sale-seller-select" @click="sellerUserId = members[(members.findIndex((member) => member.id === sellerUserId) + 1) % Math.max(1, members.length)]?.id || sellerUserId" /><van-field v-model="occurredAt" label="成交时间" required type="datetime-local" data-ai-id="quick-sale-occurred-at" /><van-field v-model="salesChannel" label="销售渠道" placeholder="可选" data-ai-id="quick-sale-channel" /><van-field v-model="note" label="备注" type="textarea" rows="2" placeholder="可选" data-ai-id="quick-sale-note" /></section><section class="fee-section" data-ai-id="quick-sale-fee-section"><h2>平台手续费（可选）</h2><van-radio-group v-model="feeMode" direction="horizontal" data-ai-id="quick-sale-fee-mode"><van-radio name="none" data-ai-id="quick-sale-fee-mode-none">无</van-radio><van-radio name="percentage" data-ai-id="quick-sale-fee-mode-percentage">按比例</van-radio><van-radio name="amount" data-ai-id="quick-sale-fee-mode-amount">按金额</van-radio></van-radio-group><van-field v-if="feeMode !== 'none'" v-model="feeValue" :label="feeMode === 'percentage' ? '手续费比例' : '手续费金额'" inputmode="decimal" placeholder="例如：1.60" data-ai-id="quick-sale-fee-value"><template #button>{{ feeMode === 'percentage' ? '%' : '元' }}</template></van-field><p v-if="feePreview !== null && receivedPreview !== null" class="notice" data-ai-id="quick-sale-fee-preview">手续费 ¥{{ feePreview.toFixed(2) }}，预计实收 ¥{{ receivedPreview.toFixed(2) }}</p></section>
      <h2>商品</h2>
      <section data-ai-id="quick-sale-item-list">
        <article v-for="item in items" :key="item.id" class="item-card" :data-ai-id="`quick-sale-item-${item.id}`">
          <header><strong>商品项</strong><button class="icon-button" type="button" aria-label="删除商品项" title="删除商品项" :data-ai-id="`quick-sale-item-${item.id}-remove`" @click="askRemoveItem(item.id)"><van-icon name="delete-o" /></button></header>
          <van-field v-model="item.name" label="商品名" required placeholder="可自由填写" :data-ai-id="`quick-sale-item-${item.id}-name`" />
          <div class="number-row"><span>售出数量</span><van-stepper :model-value="item.quantity" min="1" :data-ai-id="`quick-sale-item-${item.id}-quantity`" @change="setQuantity(item, Number($event))" /></div>
          <van-field v-model="item.cost" label="本单成本" required inputmode="decimal" :data-ai-id="`quick-sale-item-${item.id}-cost`"><template #button><van-button size="small" :disabled="!canFillCost(item)" :data-ai-id="`quick-sale-item-${item.id}-cost-fill`" @click="fillCost(item)">按库存成本</van-button></template></van-field>
          <div class="number-row"><span>关联库存</span><van-switch :model-value="item.linkEnabled" :data-ai-id="`quick-sale-item-${item.id}-link-toggle`" @update:model-value="enableLink(item)" /></div>
          <div v-if="item.linkEnabled" class="consumption-list" :data-ai-id="`quick-sale-item-${item.id}-inventory-list`"><div class="inventory-action"><van-button text="添加关联库存" type="primary" :data-ai-id="`quick-sale-item-${item.id}-inventory-pick`" @click="openPicker(item)" /></div><div v-for="entry in itemInventory(item)" :key="entry.productId" class="consumption" :data-ai-id="`quick-sale-item-${item.id}-inventory-item-${entry.productId}`"><span>{{ entry.product?.productName }}<small>可用 {{ availableFor(item, entry.productId) }} 件</small></span><van-stepper :model-value="entry.quantity" min="1" :max="availableFor(item, entry.productId)" :data-ai-id="`quick-sale-item-${item.id}-inventory-item-${entry.productId}-qty`" @change="updateConsumption(item, entry.productId, Number($event))" /><button class="icon-button" type="button" aria-label="移除关联库存" title="移除关联库存" :data-ai-id="`quick-sale-item-${item.id}-inventory-item-${entry.productId}-remove`" @click="askRemoveConsumption(item.id, entry.productId)"><van-icon name="delete-o" /></button></div></div>
        </article>
      </section>
      <van-button block class="tl-button--secondary" data-ai-id="quick-sale-add-item" @click="addItem">添加商品项</van-button><footer><van-button block type="primary" :loading="saving" data-ai-id="quick-sale-submit" @click="save">保存并扣减库存</van-button></footer></main>
    <van-popup v-model:show="showPicker" position="bottom" round data-ai-id="inventory-picker-popup"><section class="picker" data-ai-id="inventory-picker-sheet"><h2>选择关联库存</h2><van-checkbox-group v-model="pickedIds"><van-cell-group inset><van-cell v-for="product in inventory" :key="product.productId" :data-ai-id="`inventory-picker-item-${product.productId}`" :title="product.productName" :label="`可用 ${availableFor(selectedItem || items[0], product.productId)} 件`" clickable @click="!pickedIds.includes(product.productId) ? pickedIds.push(product.productId) : pickedIds.splice(pickedIds.indexOf(product.productId), 1)"><template #right-icon><van-checkbox :name="product.productId" :data-ai-id="`inventory-picker-item-${product.productId}-check`" @click.stop /></template></van-cell></van-cell-group></van-checkbox-group><div class="picker-actions"><van-button class="tl-button--secondary" data-ai-id="inventory-picker-cancel" @click="showPicker = false">取消</van-button><van-button type="primary" data-ai-id="inventory-picker-confirm" @click="confirmPicker">确认关联</van-button></div></section></van-popup>
    <van-dialog v-model:show="showMismatch" title="数量不一致" show-cancel-button data-ai-id="quick-sale-mismatch-dialog" @confirm="confirmMismatch"><p style="margin:0;padding:0 16px;color:#536078;line-height:1.5">部分商品售出数量与关联库存数量不一致，系统不会修改任何数量。仍按填写值继续保存？</p></van-dialog>
    <DangerConfirmDialog :show="Boolean(removeTarget)" title="确认删除" :message="removeTarget?.type === 'item' ? '删除这行商品？' : '移除这项关联库存？'" confirm-text="删除" ai-id="quick-sale-remove-confirm-dialog" @update:show="(value) => !value && (removeTarget = null)" @confirm="confirmRemove" />
  </div>
</template>

<style scoped>.quick-sale-form-page{min-height:100vh;padding-bottom:72px;background:#f5f7fb}.content{padding:16px}.notice,.muted{color:#71809a;font-size:12px;line-height:1.5}.notice{margin:0 0 12px}.card,.item-card{overflow:hidden;border-radius:10px;background:#fff;box-shadow:0 1px 0 #e4e8f0}.item-card{margin:10px 0}.item-card header{display:flex;min-height:44px;align-items:center;justify-content:space-between;padding:0 12px;border-bottom:1px solid #edf0f5}.icon-button{display:grid;width:36px;height:36px;place-items:center;border:0;border-radius:8px;background:transparent;color:#b42318;font:inherit}.icon-button :deep(.van-icon){font-size:18px}.number-row,.consumption{display:flex;min-height:52px;align-items:center;justify-content:space-between;gap:10px;padding:8px 12px;border-bottom:1px solid #edf0f5}.number-row>span{font-size:14px}.consumption span{min-width:0;flex:1}.consumption small{display:block;color:#71809a;font-size:12px}.consumption-list{padding-bottom:8px}.inventory-action{display:flex;min-height:44px;align-items:center;justify-content:flex-end;padding:0 12px;border-bottom:1px solid #edf0f5}.inventory-action :deep(.van-button){min-height:44px;padding:0 4px;border:0;background:transparent;color:#3657c8;font-size:14px}.inventory-action :deep(.van-button:active){background:#eef2ff}.picker{padding:16px 16px calc(16px + env(safe-area-inset-bottom))}.picker h2{margin:0 0 12px;font-size:17px}.picker-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.picker-actions :deep(.van-button){min-height:44px}h2{margin:20px 0 8px;font-size:17px}footer{margin-top:16px}footer :deep(.van-button){min-height:44px}.state{display:grid;min-height:60vh;place-items:center}.fee-section{margin:12px 0;padding:12px;border:1px solid #edf0f5;border-radius:10px;background:#fff}.fee-section h2{margin:0 0 10px;font-size:14px}.fee-section :deep(.van-radio-group){gap:20px;margin-bottom:8px}.fee-section :deep(.van-radio__label){font-size:14px}</style>
