<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { api, type SettlementIndex } from '../api';
import { formatDateTime } from '../utils/dateTime';
import AppBottomNavigation from '../components/AppBottomNavigation.vue';
const route = useRoute(); const router = useRouter(); const batchId = computed(() => String(route.params.id));
const data = ref<SettlementIndex | null>(null); const loading = ref(true); const error = ref('');
async function load() { loading.value = true; error.value = ''; try { data.value = (await api.get<SettlementIndex>(`/batches/${batchId.value}/settlements`)).data; } catch { error.value = '结算数据加载失败，请重试'; } finally { loading.value = false; } }
onMounted(load);
</script>
<template><div class="settlement-page" data-ai-id="settlement-page"><van-nav-bar title="结算" left-text="返回" left-arrow @click-left="router.push(`/batches/${batchId}`)"/><div v-if="loading" class="state"><van-loading/></div><van-empty v-else-if="error" :description="error"><van-button type="primary" size="small" @click="load">重试</van-button></van-empty><main v-else-if="data" class="content"><h1>结算</h1><p class="muted">{{ data.unsettledSaleCount ? `当前有 ${data.unsettledSaleCount} 笔销售可结算` : '暂无未结账销售' }}</p><van-button v-if="data.canManage && data.unsettledSaleCount" block type="primary" data-ai-id="settlement-start" @click="router.push(`/batches/${batchId}/settlements/new`)">开始结算</van-button><p v-else-if="!data.canManage" class="readonly">只读权限 · 当前角色只能查看已确认账单。</p><section data-ai-id="settlement-adjustment-list"><h2>待处理调整</h2><van-empty v-if="!data.adjustments.length" description="暂无待确认调整单"/><div v-else class="bill-list"><button v-for="item in data.adjustments" :key="item.id" class="bill-item" :data-ai-id="`settlement-adjustment-${item.id}`" @click="router.push(`/batches/${batchId}/settlement-adjustments/${item.id}`)"><span><strong>待确认结算调整</strong><small>成本 ¥{{ item.oldCost }} → ¥{{ item.newCost }}</small></span><van-icon name="arrow"/></button></div></section><section><h2>已确认账单</h2><van-empty v-if="!data.bills.length" description="暂无已确认账单"/><div v-else class="bill-list" data-ai-id="settlement-confirmed-list"><button v-for="bill in data.bills" :key="bill.id" class="bill-item" :data-ai-id="`settlement-bill-${bill.id}`" @click="router.push(`/batches/${batchId}/settlements/${bill.id}`)"><span><strong>{{ formatDateTime(bill.confirmedAt) }} 阶段账单</strong><small>{{ bill.saleCount }} 笔销售 · 利润 ¥{{ bill.profitTotal }}</small></span><van-icon name="arrow"/></button></div></section></main><AppBottomNavigation/></div></template>
<style scoped>.settlement-page{min-height:100vh;padding-bottom:66px;background:#f5f7fb}.settlement-page :deep(.van-nav-bar){position:sticky;top:0;z-index:2}.content{padding:20px 16px 32px}.content h1{margin:0 0 5px;font-size:24px}.muted{margin:0 0 16px;color:#71809a;font-size:13px}.content :deep(.van-button){min-height:44px}.readonly{margin:0 0 18px;padding:10px 12px;border-radius:8px;background:#edf1ff;color:#2949aa;font-size:13px}.content section{margin-top:26px}.content h2{margin:0 0 10px;font-size:17px}.bill-list{overflow:hidden;border-radius:10px;background:#fff}.bill-item{display:flex;width:100%;min-height:66px;align-items:center;justify-content:space-between;gap:10px;padding:11px 12px;border:0;border-bottom:1px solid #e4e8f0;background:#fff;color:#172033;text-align:left;font:inherit}.bill-item:last-child{border:0}.bill-item strong,.bill-item small{display:block}.bill-item small{margin-top:5px;color:#71809a;font-size:12px}.state{display:grid;min-height:60vh;place-items:center}</style>
