-- B5：所有财务金额统一改为分，并在销售上固化可选渠道和手续费快照。
-- 本迁移由 schema_migrations 保证只执行一次；执行前必须完成数据库备份。
ALTER TABLE inventory_purchases RENAME COLUMN total_cost_tenths TO total_cost_cents;
ALTER TABLE purchase_cost_shares RENAME COLUMN amount_tenths TO amount_cents;
ALTER TABLE listings RENAME COLUMN display_price_tenths TO display_price_cents;
ALTER TABLE inventory_adjustments RENAME COLUMN consumed_cost_tenths TO consumed_cost_cents;
ALTER TABLE sales RENAME COLUMN total_price_tenths TO total_price_cents;
ALTER TABLE sales RENAME COLUMN consumed_cost_tenths TO consumed_cost_cents;
ALTER TABLE expenses RENAME COLUMN amount_tenths TO amount_cents;
ALTER TABLE sale_cost_allocations RENAME COLUMN amount_tenths TO amount_cents;
ALTER TABLE settlement_bills RENAME COLUMN sale_total_tenths TO sale_total_cents;
ALTER TABLE settlement_bills RENAME COLUMN expense_total_tenths TO expense_total_cents;
ALTER TABLE settlement_bills RENAME COLUMN cost_total_tenths TO cost_total_cents;
ALTER TABLE settlement_bills RENAME COLUMN profit_total_tenths TO profit_total_cents;
ALTER TABLE settlement_bill_sales RENAME COLUMN total_price_tenths TO total_price_cents;
ALTER TABLE settlement_bill_sales RENAME COLUMN consumed_cost_tenths TO consumed_cost_cents;
ALTER TABLE settlement_bill_expenses RENAME COLUMN amount_tenths TO amount_cents;
ALTER TABLE settlement_cost_shares RENAME COLUMN amount_tenths TO amount_cents;
ALTER TABLE settlement_profit_shares RENAME COLUMN amount_tenths TO amount_cents;
ALTER TABLE settlement_member_results RENAME COLUMN cost_share_tenths TO cost_share_cents;
ALTER TABLE settlement_member_results RENAME COLUMN cost_recovery_tenths TO cost_recovery_cents;
ALTER TABLE settlement_member_results RENAME COLUMN sales_received_tenths TO sales_received_cents;
ALTER TABLE settlement_member_results RENAME COLUMN purchases_paid_tenths TO purchases_paid_cents;
ALTER TABLE settlement_member_results RENAME COLUMN expenses_paid_tenths TO expenses_paid_cents;
ALTER TABLE settlement_member_results RENAME COLUMN profit_amount_tenths TO profit_amount_cents;
ALTER TABLE settlement_member_results RENAME COLUMN net_tenths TO net_cents;
ALTER TABLE settlement_transfer_suggestions RENAME COLUMN amount_tenths TO amount_cents;
ALTER TABLE purchase_corrections RENAME COLUMN old_total_cost_tenths TO old_total_cost_cents;
ALTER TABLE purchase_corrections RENAME COLUMN new_total_cost_tenths TO new_total_cost_cents;
ALTER TABLE purchase_correction_cost_shares RENAME COLUMN amount_tenths TO amount_cents;
ALTER TABLE settlement_adjustment_bills RENAME COLUMN old_cost_tenths TO old_cost_cents;
ALTER TABLE settlement_adjustment_bills RENAME COLUMN new_cost_tenths TO new_cost_cents;
ALTER TABLE settlement_adjustment_member_results RENAME COLUMN old_cost_share_tenths TO old_cost_share_cents;
ALTER TABLE settlement_adjustment_member_results RENAME COLUMN new_cost_share_tenths TO new_cost_share_cents;
ALTER TABLE settlement_adjustment_member_results RENAME COLUMN old_purchase_paid_tenths TO old_purchase_paid_cents;
ALTER TABLE settlement_adjustment_member_results RENAME COLUMN new_purchase_paid_tenths TO new_purchase_paid_cents;
ALTER TABLE settlement_adjustment_member_results RENAME COLUMN net_delta_tenths TO net_delta_cents;
ALTER TABLE settlement_adjustment_transfers RENAME COLUMN amount_tenths TO amount_cents;

UPDATE inventory_purchases SET total_cost_cents=total_cost_cents*10;
UPDATE purchase_cost_shares SET amount_cents=amount_cents*10;
UPDATE listings SET display_price_cents=display_price_cents*10 WHERE display_price_cents IS NOT NULL;
UPDATE inventory_adjustments SET consumed_cost_cents=consumed_cost_cents*10;
UPDATE sales SET total_price_cents=total_price_cents*10, consumed_cost_cents=consumed_cost_cents*10;
UPDATE expenses SET amount_cents=amount_cents*10;
UPDATE sale_cost_allocations SET amount_cents=amount_cents*10;
UPDATE settlement_bills SET sale_total_cents=sale_total_cents*10, expense_total_cents=expense_total_cents*10, cost_total_cents=cost_total_cents*10, profit_total_cents=profit_total_cents*10;
UPDATE settlement_bill_sales SET total_price_cents=total_price_cents*10, consumed_cost_cents=consumed_cost_cents*10;
UPDATE settlement_bill_expenses SET amount_cents=amount_cents*10;
UPDATE settlement_cost_shares SET amount_cents=amount_cents*10;
UPDATE settlement_profit_shares SET amount_cents=amount_cents*10;
UPDATE settlement_member_results SET cost_share_cents=cost_share_cents*10, cost_recovery_cents=cost_recovery_cents*10, sales_received_cents=sales_received_cents*10, purchases_paid_cents=purchases_paid_cents*10, expenses_paid_cents=expenses_paid_cents*10, profit_amount_cents=profit_amount_cents*10, net_cents=net_cents*10;
UPDATE settlement_transfer_suggestions SET amount_cents=amount_cents*10;
UPDATE purchase_corrections SET old_total_cost_cents=old_total_cost_cents*10, new_total_cost_cents=new_total_cost_cents*10;
UPDATE purchase_correction_cost_shares SET amount_cents=amount_cents*10;
UPDATE settlement_adjustment_bills SET old_cost_cents=old_cost_cents*10, new_cost_cents=new_cost_cents*10;
UPDATE settlement_adjustment_member_results SET old_cost_share_cents=old_cost_share_cents*10, new_cost_share_cents=new_cost_share_cents*10, old_purchase_paid_cents=old_purchase_paid_cents*10, new_purchase_paid_cents=new_purchase_paid_cents*10, net_delta_cents=net_delta_cents*10;
UPDATE settlement_adjustment_transfers SET amount_cents=amount_cents*10;
ALTER TABLE products ALTER COLUMN reference_price TYPE numeric(12,2);

ALTER TABLE sales ADD COLUMN sales_channel text;
ALTER TABLE sales ADD COLUMN fee_mode text CHECK (fee_mode IN ('percentage','amount'));
ALTER TABLE sales ADD COLUMN fee_rate_basis_points integer CHECK (fee_rate_basis_points BETWEEN 0 AND 10000);
ALTER TABLE sales ADD COLUMN service_fee_cents bigint NOT NULL DEFAULT 0 CHECK (service_fee_cents >= 0);
ALTER TABLE settlement_bills ADD COLUMN service_fee_total_cents bigint NOT NULL DEFAULT 0;
ALTER TABLE settlement_bill_sales ADD COLUMN service_fee_cents bigint NOT NULL DEFAULT 0;
